"use client";

const countryOptions = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

const regionOptionsByCountry: Record<string, string[]> = {
  Philippines: [
    "Metro Manila",
    "North Luzon",
    "South Luzon",
    "Visayas",
    "Mindanao",
  ],
};

const provinceOptionsByRegion: Record<string, string[]> = {
  "Metro Manila": ["Metro Manila"],
  "North Luzon": [
    "Abra",
    "Apayao",
    "Baguio",
    "Batanes",
    "Benguet",
    "Bulacan",
    "Cagayan",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Isabela",
    "Kalinga",
    "La Union",
    "Mountain Province",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Pampanga",
    "Pangasinan",
    "Quirino",
    "Tarlac",
    "Zambales",
  ],
  "South Luzon": [
    "Albay",
    "Aurora",
    "Batangas",
    "Camarines Norte",
    "Camarines Sur",
    "Catanduanes",
    "Cavite",
    "Laguna",
    "Marinduque",
    "Masbate",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Quezon",
    "Rizal",
    "Romblon",
    "Sorsogon",
  ],
  Visayas: [
    "Aklan",
    "Antique",
    "Biliran",
    "Bohol",
    "Capiz",
    "Cebu",
    "Eastern Samar",
    "Guimaras",
    "Iloilo",
    "Leyte",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Samar",
    "Samar",
    "Siquijor",
    "Southern Leyte",
  ],
  Mindanao: [
    "Agusan del Norte",
    "Agusan del Sur",
    "Basilan",
    "Bukidnon",
    "Camiguin",
    "Cotabato",
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Dinagat Islands",
    "Lanao del Norte",
    "Lanao del Sur",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Misamis Occidental",
    "Misamis Oriental",
    "Sarangani",
    "South Cotabato",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tawi-Tawi",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
};

const cityOptionsByProvince: Record<string, string[]> = {
  "Metro Manila": [
    "Manila",
    "Quezon City",
    "Makati",
    "Pasig",
    "Taguig",
    "Pasay",
    "Mandaluyong",
    "Paranaque",
    "Las Pinas",
    "Muntinlupa",
    "Marikina",
    "San Juan",
    "Caloocan",
    "Malabon",
    "Navotas",
    "Valenzuela",
    "Pateros",
  ],
  "Davao del Norte": [
    "Tagum City",
    "Panabo City",
    "Samal City",
    "Asuncion",
    "Braulio E. Dujali",
    "Carmen",
    "Kapalong",
    "New Corella",
    "San Isidro",
    "Santo Tomas",
    "Talaingod",
  ],
  "Davao de Oro": [
    "Monkayo",
    "Montevista",
    "Nabunturan",
    "New Bataan",
    "Mabini",
    "Maco",
    "Maragusan",
    "Mawab",
    "Pantukan",
    "Laak",
    "Compostela",
  ],
  "Davao del Sur": [
    "Digos City",
    "Bansalan",
    "Hagonoy",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Matanao",
    "Padada",
    "Santa Cruz",
    "Sulop",
  ],
  "Davao Oriental": [
    "Mati City",
    "Baganga",
    "Banaybanay",
    "Boston",
    "Caraga",
    "Cateel",
    "Governor Generoso",
    "Lupon",
    "Manay",
    "San Isidro",
    "Tarragona",
  ],
  Cebu: [
    "Cebu City",
    "Mandaue City",
    "Lapu-Lapu City",
    "Talisay City",
    "Toledo City",
    "Danao City",
    "Carcar City",
    "Naga City",
    "Bogo City",
  ],
  Iloilo: [
    "Iloilo City",
    "Passi City",
    "Miagao",
    "Oton",
    "Leganes",
    "Santa Barbara",
    "Cabatuan",
    "Pavia",
  ],
};

const barangayOptionsByCity: Record<string, string[]> = {
  "Tagum City": [
    "Apokon",
    "Bincungan",
    "Canocotan",
    "La Filipina",
    "Madaum",
    "Magdum",
    "Mankilam",
    "Nueva Fuerza",
    "Pagsabangan",
    "San Agustin",
    "Visayan Village",
  ],
  "Panabo City": [
    "A.O. Floirendo",
    "Datu Abdul Dadia",
    "Gredu",
    "J.P. Laurel",
    "Katipunan",
    "Little Panay",
    "Lower Panaga",
    "Mabunao",
    "New Malaga",
    "San Francisco",
  ],
  "Samal City": [
    "Adecor",
    "Anonang",
    "Balet",
    "Caliclic",
    "Cogon",
    "Libuak",
    "Peñaplata",
    "San Isidro",
    "Sion",
    "Tagbaobo",
  ],
  "Digos City": [
    "Aplaya",
    "Cogon",
    "Dawis",
    "Matti",
    "Rizal",
    "San Agustin",
    "San Jose",
    "Sinawilan",
    "Tres de Mayo",
    "Zone III",
  ],
  "Davao City": [
    "Agdao",
    "Bago Aplaya",
    "Buhangin",
    "Catalunan Grande",
    "Communal",
    "Indangan",
    "Matina Aplaya",
    "Mintal",
    "Sasa",
    "Talomo",
    "Toril",
  ],
  Manila: [
    "Barangay 1",
    "Barangay 20",
    "Barangay 275",
    "Barangay 395",
    "Ermita",
    "Malate",
    "Paco",
    "Pandacan",
    "Sampaloc",
    "Tondo",
  ],
  "Quezon City": [
    "Bagong Pag-asa",
    "Batasan Hills",
    "Commonwealth",
    "Culiat",
    "Holy Spirit",
    "Kaligayahan",
    "Loyola Heights",
    "Novaliches Proper",
    "Pasong Tamo",
    "Tandang Sora",
  ],
  "Cebu City": [
    "Apas",
    "Bacayan",
    "Banilad",
    "Basak San Nicolas",
    "Capitol Site",
    "Kasambagan",
    "Lahug",
    "Mabolo",
    "Talamban",
    "Tisa",
  ],
  "Iloilo City": [
    "Arevalo",
    "Calumpang",
    "City Proper",
    "Jaro",
    "La Paz",
    "Lapuz",
    "Mandurriao",
    "Molo",
    "San Rafael",
    "Ungka",
  ],
};

const fallbackProvinceOptionsByCountry: Record<string, string[]> = {
  "United States": ["California", "Texas", "New York", "Florida", "Illinois", "Washington"],
  Canada: ["Ontario", "British Columbia", "Quebec", "Alberta", "Manitoba"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Fukuoka"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Gyeonggi-do", "Daegu"],
  China: ["Beijing", "Shanghai", "Guangdong", "Sichuan", "Zhejiang"],
  India: ["Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Telangana"],
  Australia: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia"],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
};

const fallbackCityOptionsByCountry: Record<string, string[]> = {
  Philippines: ["Manila", "Quezon City", "Davao City", "Cebu City", "Tagum City"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds"],
};

export const countries = [...countryOptions];

export function getRegionOptions(country?: string) {
  return country ? regionOptionsByCountry[country] ?? [] : [];
}

export function getProvinceOptions(country?: string, region?: string) {
  if (country === "Philippines" && region) {
    return provinceOptionsByRegion[region] ?? [];
  }

  return country ? fallbackProvinceOptionsByCountry[country] ?? [] : [];
}

export function getCityOptions(country?: string, _region?: string, province?: string) {
  if (country === "Philippines" && province) {
    return cityOptionsByProvince[province] ?? [];
  }

  return country ? fallbackCityOptionsByCountry[country] ?? [] : [];
}

export function getBarangayOptions(country?: string, _province?: string, city?: string) {
  if (country === "Philippines" && city) {
    return barangayOptionsByCity[city] ?? [];
  }

  return [];
}
