export type ProductStatus = "available" | "pre-order" | "sold-out";

export type Product = {
  id: string;
  name: string;
  brand: string;
  price: number;
  stock: number;
  status: ProductStatus;
  category: "album" | "cloth" | "accessories";
  subcategory: string;
  image: string;
  gallery: string[];
  description: string;
  details: string[];
  sizes: string[];
};

export const products: Product[] = [
  {
    id: "music-001",
    name: 'Gabriela Rose Die-Cut 7" Vinyl',
    brand: "KATSEYE Music",
    price: 22.98,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "vinyl",
    image: "https://shop.katseye.world/cdn/shop/files/GabrielaVinyl_Packshot-02.png?v=1762829862&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/GabrielaVinyl_Packshot-02.png?v=1762829862&width=1000",
    ],
    description:
      'Limited-edition singles day die-cut vinyl featuring "Gabriela" on Side A and "Gabriela (JULiA LEWiS Reggaeton Remix)" on Side B.',
    details: [
      'Official KATSEYE shop music release',
      'Limited-edition die-cut 7-inch vinyl',
      'Side A: Gabriela',
      'Side B: Gabriela (JULiA LEWiS Reggaeton Remix)',
    ],
    sizes: ['7" Vinyl'],
  },
  {
    id: "music-002",
    name: "Gabriela CD Single",
    brand: "KATSEYE Music",
    price: 4.98,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "cd",
    image: "https://shop.katseye.world/cdn/shop/files/1000x1000_CD_Packshot-03_5784a25f-16dd-4ddd-bfe9-b5803c9ed33e.png?v=1746124525&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/1000x1000_CD_Packshot-03_5784a25f-16dd-4ddd-bfe9-b5803c9ed33e.png?v=1746124525&width=1000",
    ],
    description:
      "Official Gabriela CD single release from the KATSEYE music collection.",
    details: [
      "Official KATSEYE shop release",
      "Physical CD single format",
      "Collection: Music",
      "Publicly listed as available on the official store",
    ],
    sizes: ["CD Single"],
  },
  {
    id: "music-003",
    name: "BEAUTIFUL CHAOS - Official Store Exclusive Vinyl",
    brand: "KATSEYE Music",
    price: 29.99,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "vinyl",
    image: "https://shop.katseye.world/cdn/shop/files/Beautiful_Official_Store_KATSEYE_CD_Thumbnail.png?v=1749663626&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Beautiful_Official_Store_KATSEYE_CD_Thumbnail.png?v=1749663626&width=1000",
    ],
    description:
      "Official store exclusive edition of BEAUTIFUL CHAOS from the KATSEYE music collection.",
    details: [
      "Official store exclusive",
      "Music collection release",
      "Format listed by the official KATSEYE store",
      "Publicly listed as available",
    ],
    sizes: ["Exclusive Vinyl"],
  },
  {
    id: "music-004",
    name: "BEAUTIFUL CHAOS - Standard Vinyl",
    brand: "KATSEYE Music",
    price: 29.99,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "vinyl",
    image: "https://shop.katseye.world/cdn/shop/files/Beautiful__KATSEYE_CD_Thumbnail.png?v=1746138026&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Beautiful__KATSEYE_CD_Thumbnail.png?v=1746138026&width=1000",
    ],
    description:
      "Standard vinyl edition of BEAUTIFUL CHAOS as listed in the official KATSEYE music collection.",
    details: [
      "Standard edition",
      "Official KATSEYE music collection item",
      "Publicly listed as available",
      "Album artwork from the official store",
    ],
    sizes: ["Standard Vinyl"],
  },
  {
    id: "music-005",
    name: "BEAUTIFUL CHAOS (EXTENDED VER.) - DIGITAL EP",
    brand: "KATSEYE Music",
    price: 7.99,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "digital",
    image: "https://shop.katseye.world/cdn/shop/files/DigitalAlbum.jpg?v=1746137262&width=1500",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/DigitalAlbum.jpg?v=1746137262&width=1500",
    ],
    description:
      "KATSEYE's 2nd EP in digital format, delivered by email, with the seven-track extended version listed on the official store.",
    details: [
      "Digital EP",
      "Seven-track extended version",
      "Delivery by email from the official store",
      "U.S. customers only per store listing",
    ],
    sizes: ["Digital"],
  },
  {
    id: "music-006",
    name: 'KATSEYE - Touch 7" Vinyl',
    brand: "KATSEYE Music",
    price: 15.0,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "vinyl",
    image: "https://shop.katseye.world/cdn/shop/files/Vinyl_Packshot_01_b043dab3-5bb0-4189-986a-39adbd3d2af5.png?v=1733353759&width=3000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Vinyl_Packshot_01_b043dab3-5bb0-4189-986a-39adbd3d2af5.png?v=1733353759&width=3000",
    ],
    description:
      'Official 7" vinyl release for "Touch" from the KATSEYE music collection.',
    details: [
      'Official KATSEYE "Touch" release',
      '7-inch vinyl format',
      "Music collection listing",
      "Publicly listed as available",
    ],
    sizes: ['7" Vinyl'],
  },
  {
    id: "music-007",
    name: 'KATSEYE - "SIS (Soft Is Strong)" - Vinyl',
    brand: "KATSEYE Music",
    price: 29.99,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "vinyl",
    image: "https://shop.katseye.world/cdn/shop/files/1000x1000_CD_Packshot-03_5784a25f-16dd-4ddd-bfe9-b5803c9ed33e.png?v=1746124525&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/1000x1000_CD_Packshot-03_5784a25f-16dd-4ddd-bfe9-b5803c9ed33e.png?v=1746124525&width=1000",
    ],
    description:
      'Official "SIS (Soft Is Strong)" physical music release from the KATSEYE store.',
    details: [
      'Official KATSEYE "SIS (Soft Is Strong)" release',
      "Physical format listed on the official shop",
      "Music collection item",
      "Publicly listed as available",
    ],
    sizes: ["Vinyl"],
  },
  {
    id: "music-008",
    name: 'KATSEYE - "SIS (Soft Is Strong)" - Digital Album',
    brand: "KATSEYE Music",
    price: 5.99,
    stock: 1,
    status: "available",
    category: "album",
    subcategory: "digital",
    image: "https://shop.katseye.world/cdn/shop/files/DigitalAlbum.jpg?v=1746137262&width=1500",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/DigitalAlbum.jpg?v=1746137262&width=1500",
    ],
    description:
      'Digital edition of "SIS (Soft Is Strong)" from the official KATSEYE music collection.',
    details: [
      "Digital album",
      "Official KATSEYE store listing",
      "Music collection item",
      "Publicly listed as available",
    ],
    sizes: ["Digital"],
  },
  {
    id: "music-009",
    name: "BEAUTIFUL CHAOS (Chaotic Ver.) - Official Store Edition",
    brand: "KATSEYE Music",
    price: 24.98,
    stock: 0,
    status: "sold-out",
    category: "album",
    subcategory: "cd",
    image: "https://shop.katseye.world/cdn/shop/files/Beautiful_Official_Store_KATSEYE_CD_Thumbnail.png?v=1749663626&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Beautiful_Official_Store_KATSEYE_CD_Thumbnail.png?v=1749663626&width=1000",
    ],
    description:
      "Chaotic version official store edition of BEAUTIFUL CHAOS, publicly marked sold out on the official KATSEYE shop.",
    details: [
      "Official store edition",
      "Chaotic version",
      "Public status: Sold out",
      "Music collection item",
    ],
    sizes: ["CD Edition"],
  },
  {
    id: "merch-001",
    name: "Internet Girl Hoodie",
    brand: "KATSEYE Merch",
    price: 75.0,
    stock: 1,
    status: "available",
    category: "cloth",
    subcategory: "hoodies",
    image: "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Front.png?v=1767914137&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Front.png?v=1767914137&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Details_1-2.jpg?v=1767977750&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Details_3.jpg?v=1767977750&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Details_4.jpg?v=1767977750&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Hoodie_Back.png?v=1767977750&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Merch_Lifestyle_1.jpg?v=1767977750&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Merch_Lifestyle_3.jpg?v=1767977750&width=1200",
    ],
    description:
      "This hoodie captures KATSEYE's lovely and vintage-inspired mood. A playful Wi-Fi print on the sleeves adds a unique and charming detail, and the oversized fit is built for versatile styling and comfortable wear.",
    details: [
      "Official KATSEYE merch product",
      "Oversized fit",
      "Vintage-inspired Internet Girl graphic",
      "Wi-Fi print detail on the sleeves",
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "merch-002",
    name: "BEAUTIFUL CHAOS Hoodie",
    brand: "KATSEYE Merch",
    price: 90.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "hoodies",
    image: "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Detail_01.jpg?v=1769550385&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Detail_01.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Detail_04.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Detail_06.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Lifestyle_03.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_Hoodie_Lifestyle_04.jpg?v=1769550385&width=1200",
    ],
    description:
      'A rhinestone hoodie that shines like KATSEYE. The front features the tour title "Beautiful Chaos", the back showcases the KATSEYE symbol, and the sleeve is detailed with the KATSEYE logo. With its simple black base and unique rhinestone accents, this hoodie is a stylish daily item you can wear anywhere.',
    details: [
      "Official KATSEYE merch product",
      "Rhinestone Beautiful Chaos tour graphic",
      "KATSEYE symbol on the back",
      "Sleeve logo detail",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-003",
    name: "BEAUTIFUL CHAOS Zip-Up Hoodie",
    brand: "KATSEYE Merch",
    price: 100.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "hoodies",
    image: "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_01.png?v=1769568749&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_01.png?v=1769568749&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_02.png?v=1769568749&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_03.png?v=1769568749&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_04.png?v=1769568749&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_ZipHoodie_05.png?v=1769568749&width=1200",
    ],
    description:
      "A hoodie commemorating KATSEYE's 2025 NA Tour Beautiful Chaos. The front features the KATSEYE symbol, while the back showcases charms representing the members, the logo, and the tour name in a simple but striking zip-up design.",
    details: [
      "Official KATSEYE merch product",
      "Zip-up hoodie silhouette",
      "2025 NA Tour Beautiful Chaos commemorative design",
      "One random photocard included per official listing",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-004",
    name: "BEAUTIFUL CHAOS Routing T-Shirt (Black)",
    brand: "KATSEYE Merch",
    price: 50.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-Shirt_Black__01_Final.png?v=1769202723&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-Shirt_Black__01_Final.png?v=1769202723&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-Shirt_Black__02_Final.png?v=1769202723&width=1200",
    ],
    description:
      "This T-shirt commemorates KATSEYE: THE BEAUTIFUL CHAOS TOUR. The front features member visuals in a bold package-inspired layout, while the back showcases the tour routing in a receipt-style design.",
    details: [
      "Official KATSEYE merch product",
      "Beautiful Chaos Tour commemorative tee",
      "Front member visual layout",
      "Back routing print",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-005",
    name: "BEAUTIFUL CHAOS Routing T-Shirt (White)",
    brand: "KATSEYE Merch",
    price: 50.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__01.png?v=1769549886&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__01.png?v=1769549886&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__02.png?v=1769549886&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__Detail_01.jpg?v=1769549886&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__Detail_02_Final.jpg?v=1769549886&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_RoutingT-shirt_White__Detail_03.jpg?v=1769549886&width=1200",
    ],
    description:
      "This T-shirt captures KATSEYE's unique bodega-inspired vibe. The front features a checkout divider design with Beautiful Chaos, while the back shows a shopping cart filled with a 2025 NA tour receipt and playful objects.",
    details: [
      "Official KATSEYE merch product",
      "100% cotton",
      "Bodega-inspired front and back graphics",
      "Tour receipt design on the back",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-006",
    name: "Internet Girl Baby T-Shirt",
    brand: "KATSEYE Merch",
    price: 40.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/Revised_Baby_S_S_Shirt_Front.png?v=1767914253&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Revised_Baby_S_S_Shirt_Front.png?v=1767914253&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Baby_S_S_Shirt_Back.png?v=1767914253&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Baby_S_S_Shirt_Detail_1.jpg?v=1767914253&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Baby_S_S_Shirt_Detail_4.jpg?v=1767914253&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Merch_Lifestyle_1_a75ae112-20df-420b-8d1f-87b5d4174342.jpg?v=1767914670&width=1200",
    ],
    description:
      'This unique "Internet Girl" baby tee features playful memes inspired by the KATSEYE members. Made from smooth, stretchy fabric, it creates a slim silhouette with vintage-feel internet graphics and a Wi-Fi graphic on the back.',
    details: [
      "Official KATSEYE merch product",
      "Stretch baby tee silhouette",
      "Internet Girl graphic concept",
      "Back Wi-Fi graphic detail",
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "merch-007",
    name: "Internet Girl T-Shirt",
    brand: "KATSEYE Merch",
    price: 40.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/Revised_S_S_Shirt_Back.png?v=1767914177&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Revised_S_S_Shirt_Back.png?v=1767914177&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_S_S_Shirt_Detail_1.jpg?v=1767914177&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_S_S_Shirt_Detail_2.jpg?v=1767914177&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Merch_Lifestyle_1_9c351006-1398-45c2-aed4-a0a0d78b53e4.jpg?v=1767914177&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Merch_Lifestyle_3_f5aa5bec-7565-444b-9ddf-d4d3e9042a98.jpg?v=1767914177&width=1200",
    ],
    description:
      'This unique "Internet Girl" short-sleeve T-shirt features fun memes inspired by the KATSEYE members. Made from 100% cotton, it pairs a vintage-feel internet graphic on the front with a Wi-Fi graphic on the back.',
    details: [
      "Official KATSEYE merch product",
      "100% cotton",
      "Vintage-inspired Internet Girl graphics",
      "Back Wi-Fi artwork",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-008",
    name: "KATSEYE Black T-Shirt",
    brand: "KATSEYE Merch",
    price: 40.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/gnarly-shirt-front.png?v=1745875951&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/gnarly-shirt-front.png?v=1745875951&width=1000",
      "https://shop.katseye.world/cdn/shop/files/gnarly-shirt-back.png?v=1745875951&width=1000",
    ],
    description:
      'Black T-shirt featuring front and back graphics inspired by KATSEYE\'s song "Gnarly."',
    details: [
      "Official KATSEYE merch product",
      "Front and back Gnarly-inspired graphics",
      "Black tee base",
      "Official store merch listing",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-009",
    name: "BEAUTIFUL CHAOS Distressed T-Shirt",
    brand: "KATSEYE Merch",
    price: 35.0,
    stock: 0,
    status: "sold-out",
    category: "cloth",
    subcategory: "t-shirts",
    image: "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Details_01.jpg?v=1769550385&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Details_01.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Details_04.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Details_05.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Lifestyle_01.jpg?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_S_ST-shirt_Distressed_Black__Lifestyle_03.jpg?v=1769550385&width=1200",
    ],
    description:
      'A VHS-style T-shirt inspired by KATSEYE\'s "M.I.A" music video. The bold eye graphic and distressed details create an edgy look in a relaxed 100% cotton silhouette.',
    details: [
      "Official KATSEYE merch product",
      "100% cotton",
      "Relaxed fit",
      "Distressed VHS-style M.I.A inspired graphic",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: "merch-010",
    name: "Internet Girl Ball Cap",
    brand: "KATSEYE Accessories",
    price: 40.0,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "caps",
    image: "https://shop.katseye.world/cdn/shop/files/Katseye_BallCap_Front.png?v=1767914670&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Katseye_BallCap_Front.png?v=1767914670&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Katseye_Ball_Cap_detail_1.jpg?v=1767914677&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Katseye_Ball_Cap_detail_2.jpg?v=1767914677&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Katseye_Ball_Cap_detail_3.jpg?v=1767914677&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Katseye_Ball_Cap_detail_4.jpg?v=1767914677&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Katseye_Ball_Cap_detail_5.jpg?v=1767914677&width=1200",
    ],
    description:
      'This cute "Internet Girl" cap features an ivory base with red accents. Made in a relaxed fit, it works as a comfortable statement piece and includes lyric embroidery on the side.',
    details: [
      "Official KATSEYE accessory product",
      "Relaxed fit cap",
      "Lyric embroidery on the side",
      "Internet Girl merch collection",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-011",
    name: "KATSEYE Dad Hat (Black)",
    brand: "KATSEYE Accessories",
    price: 35.0,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "caps",
    image: "https://shop.katseye.world/cdn/shop/files/katseye-hat.png?v=1745876300&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/katseye-hat.png?v=1745876300&width=1000",
      "https://shop.katseye.world/cdn/shop/files/katseye-hat-back.png?v=1745876300&width=1000",
    ],
    description:
      'Black dad hat featuring graphics inspired by KATSEYE\'s song "Gnarly."',
    details: [
      "Official KATSEYE accessory product",
      "Black dad hat silhouette",
      "Gnarly-inspired graphic details",
      "Official store accessory listing",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-012",
    name: "KATSEYE Logo Beanie",
    brand: "KATSEYE Accessories",
    price: 24.99,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "caps",
    image: "https://shop.katseye.world/cdn/shop/files/KatseyeBeanie-01.png?v=1733353862&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KatseyeBeanie-01.png?v=1733353862&width=1000",
    ],
    description: "Beanie Details: 50% Recycled Polyester / 50% Acrylic. Single knit.",
    details: [
      "Official KATSEYE accessory product",
      "50% recycled polyester / 50% acrylic",
      "Single knit beanie",
      "Front logo patch",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-013",
    name: "BEAUTIFUL CHAOS City Keychain",
    brand: "KATSEYE Accessories",
    price: 25.0,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "keychain",
    image: "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_NewYork.png?v=1769202922&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_Atlanta.png?v=1769202922&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_Boston.png?v=1769202922&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_LosAngeles.png?v=1769202922&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_Minneapolis.png?v=1769202925&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_NewYork.png?v=1769202922&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_CityKeychain_Phoenix.png?v=1769202922&width=1200",
    ],
    description:
      "This city keychain celebrates KATSEYE: THE BEAUTIFUL CHAOS TOUR. Each set includes two plush square charms with member motifs and city/tour embroidery.",
    details: [
      "Official KATSEYE accessory product",
      "Two square plush charms per set",
      "Tour city embroidered variants",
      "Beautiful Chaos Tour keepsake",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-017",
    name: "Internet Girl Keypad Keyring",
    brand: "KATSEYE Accessories",
    price: 28.0,
    stock: 1,
    status: "pre-order",
    category: "accessories",
    subcategory: "keychain",
    image: "https://shop.katseye.world/cdn/shop/files/Keyring_Front.png?v=1767914869&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Keyring_Front.png?v=1767914869&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Keyring_Back.png?v=1767914869&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Keyring_detail_1.jpg?v=1767914869&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Keyring_detail_2.jpg?v=1767914869&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Keyring_detail_3.jpg?v=1767914869&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Keyring_detail_5.jpg?v=1767914869&width=1200",
    ],
    description:
      'This keycap keyring set includes four "Internet Girl" themed keycaps and six keycaps featuring the members\' charms. You can attach them to your keyboard or insert them into the keyring for flexible styling.',
    details: [
      "Official KATSEYE accessory product",
      "Pre-order item",
      "Four Internet Girl themed keycaps",
      "Six member charm keycaps",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-014",
    name: "Internet Girl Photo Strip",
    brand: "KATSEYE Accessories",
    price: 12.0,
    stock: 1,
    status: "pre-order",
    category: "accessories",
    subcategory: "photo-strip",
    image: "https://shop.katseye.world/cdn/shop/files/Katseye_Folder_Front.png?v=1767914832&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/Katseye_Folder_Front.png?v=1767914832&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Folder_detail_1.jpg?v=1767914832&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Folder_detail_2.jpg?v=1767914832&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Revised_Katseye_Folder_Lifestyle.jpg?v=1767914832&width=1200",
      "https://shop.katseye.world/cdn/shop/files/Updated_Strip_1.png?v=1767988832&width=1000",
      "https://shop.katseye.world/cdn/shop/files/Updated_Strip_2.png?v=1767988832&width=1000",
    ],
    description:
      "This 3-cut photo package features KATSEYE's emoji expressions and includes six photo strips, one for each member, in a cute collectible package.",
    details: [
      "Official KATSEYE accessory product",
      "Six 3-cut photos included",
      "One strip for each member",
      "Collectible package",
    ],
    sizes: ["One Size"],
  },
  {
    id: "merch-015",
    name: "Holiday 'Gnarly or Nice?' Wrapping Paper (Set of 2)",
    brand: "KATSEYE Accessories",
    price: 25.0,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "wrapping-paper",
    image: "https://shop.katseye.world/cdn/shop/files/WrappingPaper_01.png?v=1765231457&width=1000",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/WrappingPaper_01.png?v=1765231457&width=1000",
      "https://shop.katseye.world/cdn/shop/files/WrappingPaper_02.png?v=1764884142&width=1000",
      "https://shop.katseye.world/cdn/shop/files/GIFTWRAP.jpg?v=1765231457&width=1000",
      "https://shop.katseye.world/cdn/shop/files/GIFTWRAP3.png?v=1765231457&width=1000",
      "https://shop.katseye.world/cdn/shop/files/KatseyeGroup6.png?v=1765231457&width=1000",
      "https://shop.katseye.world/cdn/shop/files/Untitled-12.png?v=1765231457&width=1000",
    ],
    description:
      "Holiday wrapping paper decorated with hand-drawn illustrations by the KATSEYE members, offered in red and green versions for festive gift wrapping.",
    details: [
      "Official KATSEYE accessory product",
      "Set of 2 wrapping paper designs",
      "Hand-drawn member illustrations",
      "Holiday merch release",
    ],
    sizes: ["Set of 2"],
  },
  {
    id: "merch-016",
    name: "BEAUTIFUL CHAOS Slogan Muffler",
    brand: "KATSEYE Accessories",
    price: 35.0,
    stock: 0,
    status: "sold-out",
    category: "accessories",
    subcategory: "slogan-muffler",
    image: "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_01.png?v=1769202610&width=1200",
    gallery: [
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_01.png?v=1769202610&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_02.png?v=1769550385&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_Detail_03.jpg?v=1769551003&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_Detail_04.jpg?v=1769551003&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_Detail_05.jpg?v=1769551003&width=1200",
      "https://shop.katseye.world/cdn/shop/files/KE_SloganMuffler_Detail_06.jpg?v=1769551003&width=1200",
    ],
    description:
      "A knitted slogan scarf celebrating KATSEYE: THE BEAUTIFUL CHAOS TOUR. The bold yellow base and member charm details make it usable as both a cheering slogan and a fashion accessory.",
    details: [
      "Official KATSEYE accessory product",
      "Knitted slogan scarf",
      "Beautiful Chaos Tour item",
      "Member charm details",
    ],
    sizes: ["One Size"],
  },
];

export const getProductById = (id: string) => products.find((product) => product.id === id);

export const getProductsByCategory = (category: Product["category"]) =>
  products.filter((product) => product.category === category);

export const getProductsBySubcategory = (subcategory: string) =>
  products.filter((product) => product.subcategory === subcategory);
