"use client";

import { useSyncExternalStore } from "react";

export const STORE_SETTINGS_EVENT = "katseye:store-settings";
export const LANGUAGE_STORAGE_KEY = "katseye-language";
export const CURRENCY_STORAGE_KEY = "katseye-currency";

export type StoreLanguage = "English" | "Filipino" | "Korean" | "Japanese";
export type StoreCurrency = "PHP" | "USD" | "KRW" | "JPY";

type CurrencyConfig = {
  code: StoreCurrency;
  label: string;
  locale: string;
  rate: number;
};

export const currencyOptions: CurrencyConfig[] = [
  { code: "PHP", label: "Philippines | PHP \u20b1", locale: "en-PH", rate: 56 },
  { code: "USD", label: "United States | USD $", locale: "en-US", rate: 1 },
  { code: "KRW", label: "South Korea | KRW \u20a9", locale: "ko-KR", rate: 1320 },
  { code: "JPY", label: "Japan | JPY \u00a5", locale: "ja-JP", rate: 149 },
];

export const languageOptions: StoreLanguage[] = [
  "English",
  "Filipino",
  "Korean",
  "Japanese",
];

const translations = {
  English: {
    home: "Home",
    shop: "Shop",
    album: "Album",
    ourProduct: "Our Product",
    apparel: "Apparel",
    accessories: "Accessories",
    allApparel: "All Apparel",
    allAccessories: "All Accessories",
    tShirts: "T-Shirts",
    hoodies: "Hoodies",
    caps: "Caps",
    keychain: "Keychain",
    photoStrip: "Photo Strip",
    wrappingPaper: "Wrapping Paper",
    sloganMuffler: "Slogan Muffler",
    notifications: "Notifications",
    viewAllNotifications: "View All Notifications",
    myProfile: "My Profile",
    myOrders: "My Orders",
    settings: "Settings",
    logOut: "Log Out",
    language: "Language",
    currency: "Currency",
    shoppingCart: "Shopping Cart",
    shippingDetails: "Shipping Details",
    paymentOption: "Payment Option",
    reviewItems: "Review your items before moving to shipping details.",
    yourCartIsEmpty: "Your cart is empty.",
    continueShopping: "Continue Shopping",
    officialInCart: "Official KATSEYE product in your shopping cart.",
    youMayAlsoBeInterested: "You may also be interested",
    shippingInsurance: "Shipping Insurance",
    protectTransit: "Protect your order from loss, theft, or damage in transit.",
    orderSummary: "Order Summary",
    subTotal: "Sub Total",
    shipping: "Shipping",
    tax: "Tax",
    totalPayable: "Total Payable",
    proceedToCheckout: "Proceed to Secure Checkout",
    satisfactionTitle: "Your Satisfaction Is Guaranteed",
    satisfactionText: "We only surface curated KATSEYE products here. If something is wrong with your order, contact support and we will help with the next steps.",
    orderConfirmed: "Order Confirmed",
    yourOrderPlaced: "Your order has been placed.",
    shippingTo: "Shipping to",
    viewOrders: "View Orders",
    enterShippingDetails: "Enter the address and contact details needed for delivery.",
    choosePaymentMethod: "Choose a payment method and review the shipping address.",
    back: "Back",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    country: "Country",
    city: "City",
    postalCode: "Postal Code",
    streetAddress: "Street Address",
    selectedShippingAddress: "Selected Shipping Address",
    continueToPayment: "Continue to Payment",
    placeOrder: "Place Order",
    completeShipping: "Complete all shipping details before continuing.",
    emptyCart: "Your cart is empty.",
    creditDebitCard: "Credit / Debit Card",
    creditDebitCardDesc: "Visa, Mastercard, AMEX accepted.",
    paypal: "PayPal",
    paypalDesc: "Pay using your PayPal balance or linked card.",
    cashOnDelivery: "Cash on Delivery",
    cashOnDeliveryDesc: "Pay when your package arrives.",
    activeOrders: "Active Orders",
    upcoming: "Upcoming",
    cancelled: "Cancelled",
    received: "Received",
    orders: "Orders",
    customerName: "Customer Name",
    customerContact: "Customer Contact",
    deliveryAddress: "Delivery Address",
    seller: "Seller",
    sellerSupport: "Seller Support",
    trackingNo: "Tracking No.",
    yourOrderIs: "Your order is",
    latestTrackingUpdate: "Latest update shown below in the tracking history.",
    returnOrder: "Return Order",
    exchangeItem: "Exchange Item",
    forDeliveryQueries: "For delivery queries",
    contactUs: "Contact Us",
    trackingHistory: "Tracking History",
    noOrdersYet: "No orders in this section yet.",
    accountProfile: "My Account / Profile",
    personalDetails: "Personal details",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    nationality: "Nationality",
    address: "Address",
    email: "Email",
    resetPassword: "Reset Password",
    resetHint: "Open this section with `?tab=reset` when you want to update the password.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    savePassword: "Save Password",
    featured: "Featured",
    lowestToHighest: "Lowest to Highest",
    highestToLowest: "Highest to Lowest",
    priceRange: "Price Range",
    upTo: "Up to",
    searchProducts: "Search products",
    results: "results",
    available: "Available",
    preOrder: "Pre-Order",
    soldOut: "Sold out",
    unavailable: "Unavailable",
    addToCart: "Add to cart",
    noProductsFound: "No products found.",
    tryDifferentSearch: "Try a different search or raise the price range.",
    selectSize: "Select Size",
    quantity: "Quantity",
    outOfStock: "Out of stock",
    buyItNow: "Buy it now",
    description: "Description",
    shippingReturns: "Shipping & Returns",
    shippingReturnsText: "Ships in 2-4 business days. 14-day return window.",
    details: "Details",
    productNotFound: "Product not found.",
    backToProducts: "Back to products",
    ordersLabel: "Orders",
    on: "On",
  },
  Filipino: {
    home: "Bahay",
    shop: "Tindahan",
    album: "Album",
    ourProduct: "Mga Produkto",
    apparel: "Damit",
    accessories: "Aksesorya",
    allApparel: "Lahat ng Damit",
    allAccessories: "Lahat ng Aksesorya",
    tShirts: "T-Shirt",
    hoodies: "Hoodie",
    caps: "Sumbrero",
    keychain: "Susing Palawit",
    photoStrip: "Photo Strip",
    wrappingPaper: "Pambalot na Papel",
    sloganMuffler: "Slogan Muffler",
    notifications: "Mga Abiso",
    viewAllNotifications: "Tingnan ang Lahat ng Abiso",
    myProfile: "Aking Profile",
    myOrders: "Aking Mga Order",
    settings: "Mga Setting",
    logOut: "Mag Log Out",
    language: "Wika",
    currency: "Salapi",
    shoppingCart: "Shopping Cart",
    shippingDetails: "Detalye ng Pagpapadala",
    paymentOption: "Paraan ng Pagbabayad",
    reviewItems: "Suriin ang iyong mga item bago magpatuloy sa detalye ng pagpapadala.",
    yourCartIsEmpty: "Walang laman ang iyong cart.",
    continueShopping: "Magpatuloy sa Pamimili",
    officialInCart: "Opisyal na produktong KATSEYE sa iyong shopping cart.",
    youMayAlsoBeInterested: "Maaaring magustuhan mo rin",
    shippingInsurance: "Seguro sa Pagpapadala",
    protectTransit: "Protektahan ang iyong order laban sa pagkawala, pagnanakaw, o pinsala habang ibinibiyahe.",
    orderSummary: "Buod ng Order",
    subTotal: "Kabuuang Halaga",
    shipping: "Padala",
    tax: "Buwis",
    totalPayable: "Kabuuang Babayaran",
    proceedToCheckout: "Magpatuloy sa Checkout",
    satisfactionTitle: "Garantiya ang Iyong Kasiyahan",
    satisfactionText: "Tanging piling produktong KATSEYE lamang ang ipinapakita namin rito. Kung may mali sa iyong order, makipag-ugnayan sa support at tutulungan ka namin.",
    orderConfirmed: "Kumpirmado ang Order",
    yourOrderPlaced: "Naipasa na ang iyong order.",
    shippingTo: "Ipadadala sa",
    viewOrders: "Tingnan ang Mga Order",
    enterShippingDetails: "Ilagay ang address at contact details na kailangan para sa delivery.",
    choosePaymentMethod: "Pumili ng paraan ng pagbabayad at suriin ang shipping address.",
    back: "Bumalik",
    fullName: "Buong Pangalan",
    phoneNumber: "Numero ng Telepono",
    country: "Bansa",
    city: "Lungsod",
    postalCode: "Postal Code",
    streetAddress: "Address sa Kalye",
    selectedShippingAddress: "Napiling Shipping Address",
    continueToPayment: "Magpatuloy sa Pagbabayad",
    placeOrder: "Ilagay ang Order",
    completeShipping: "Kumpletuhin muna ang lahat ng detalye ng pagpapadala.",
    emptyCart: "Walang laman ang iyong cart.",
    creditDebitCard: "Credit / Debit Card",
    creditDebitCardDesc: "Tinatanggap ang Visa, Mastercard, at AMEX.",
    paypal: "PayPal",
    paypalDesc: "Magbayad gamit ang iyong PayPal balance o naka-link na card.",
    cashOnDelivery: "Cash on Delivery",
    cashOnDeliveryDesc: "Magbayad pagdating ng package.",
    activeOrders: "Aktibong Order",
    upcoming: "Paparating",
    cancelled: "Kinansela",
    received: "Natanggap",
    orders: "Mga Order",
    customerName: "Pangalan ng Customer",
    customerContact: "Contact ng Customer",
    deliveryAddress: "Address ng Delivery",
    seller: "Nagbebenta",
    sellerSupport: "Suporta ng Seller",
    trackingNo: "Tracking No.",
    yourOrderIs: "Ang iyong order ay",
    latestTrackingUpdate: "Makikita sa ibaba ang pinakahuling update sa tracking history.",
    returnOrder: "Ibalik ang Order",
    exchangeItem: "Palitan ang Item",
    forDeliveryQueries: "Para sa tanong sa delivery",
    contactUs: "Makipag-ugnayan",
    trackingHistory: "Kasaysayan ng Tracking",
    noOrdersYet: "Wala pang order sa seksyong ito.",
    accountProfile: "Aking Account / Profile",
    personalDetails: "Personal na detalye",
    dateOfBirth: "Petsa ng Kapanganakan",
    gender: "Kasarian",
    nationality: "Nasyonalidad",
    address: "Address",
    email: "Email",
    resetPassword: "I-reset ang Password",
    resetHint: "Buksan ang seksyong ito gamit ang `?tab=reset` kapag nais mong palitan ang password.",
    newPassword: "Bagong password",
    confirmPassword: "Kumpirmahin ang password",
    savePassword: "I-save ang Password",
    featured: "Itinatampok",
    lowestToHighest: "Mababa hanggang Mataas",
    highestToLowest: "Mataas hanggang Mababa",
    priceRange: "Saklaw ng Presyo",
    upTo: "Hanggang",
    searchProducts: "Maghanap ng produkto",
    results: "resulta",
    available: "May Stock",
    preOrder: "Pre-Order",
    soldOut: "Sold out",
    unavailable: "Hindi available",
    addToCart: "Idagdag sa cart",
    noProductsFound: "Walang nahanap na produkto.",
    tryDifferentSearch: "Subukan ang ibang paghahanap o itaas ang price range.",
    selectSize: "Piliin ang Sukat",
    quantity: "Dami",
    outOfStock: "Ubos na",
    buyItNow: "Bilhin na ngayon",
    description: "Paglalarawan",
    shippingReturns: "Shipping at Returns",
    shippingReturnsText: "Ipinapadala sa loob ng 2-4 na araw ng negosyo. May 14-araw na return window.",
    details: "Detalye",
    productNotFound: "Hindi nakita ang produkto.",
    backToProducts: "Bumalik sa mga produkto",
    ordersLabel: "Mga Order",
    on: "Bukas",
  },
  Korean: {
    home: "홈",
    shop: "쇼핑",
    album: "앨범",
    ourProduct: "상품",
    apparel: "의류",
    accessories: "액세서리",
    allApparel: "전체 의류",
    allAccessories: "전체 액세서리",
    tShirts: "티셔츠",
    hoodies: "후디",
    caps: "모자",
    keychain: "키링",
    photoStrip: "포토 스트립",
    wrappingPaper: "포장지",
    sloganMuffler: "슬로건 머플러",
    notifications: "알림",
    viewAllNotifications: "모든 알림 보기",
    myProfile: "내 프로필",
    myOrders: "내 주문",
    settings: "설정",
    logOut: "로그아웃",
    language: "언어",
    currency: "통화",
    shoppingCart: "장바구니",
    shippingDetails: "배송 정보",
    paymentOption: "결제 방법",
    reviewItems: "배송 정보로 이동하기 전에 상품을 확인하세요.",
    yourCartIsEmpty: "장바구니가 비어 있습니다.",
    continueShopping: "쇼핑 계속하기",
    officialInCart: "장바구니에 담긴 공식 KATSEYE 상품입니다.",
    youMayAlsoBeInterested: "이 상품도 좋아할 수 있어요",
    shippingInsurance: "배송 보험",
    protectTransit: "배송 중 분실, 도난 또는 파손으로부터 주문을 보호하세요.",
    orderSummary: "주문 요약",
    subTotal: "상품 금액",
    shipping: "배송비",
    tax: "세금",
    totalPayable: "총 결제 금액",
    proceedToCheckout: "안전 결제로 진행",
    satisfactionTitle: "만족을 보장합니다",
    satisfactionText: "엄선된 KATSEYE 상품만 제공됩니다. 주문에 문제가 있으면 지원팀에 문의해 주세요.",
    orderConfirmed: "주문 확인됨",
    yourOrderPlaced: "주문이 완료되었습니다.",
    shippingTo: "배송지",
    viewOrders: "주문 보기",
    enterShippingDetails: "배송에 필요한 주소와 연락처를 입력하세요.",
    choosePaymentMethod: "결제 방법을 선택하고 배송 주소를 확인하세요.",
    back: "뒤로",
    fullName: "이름",
    phoneNumber: "전화번호",
    country: "국가",
    city: "도시",
    postalCode: "우편번호",
    streetAddress: "도로명 주소",
    selectedShippingAddress: "선택한 배송지",
    continueToPayment: "결제로 계속",
    placeOrder: "주문하기",
    completeShipping: "계속하기 전에 배송 정보를 모두 입력하세요.",
    emptyCart: "장바구니가 비어 있습니다.",
    creditDebitCard: "신용 / 체크카드",
    creditDebitCardDesc: "Visa, Mastercard, AMEX 사용 가능.",
    paypal: "PayPal",
    paypalDesc: "PayPal 잔액 또는 연결된 카드로 결제하세요.",
    cashOnDelivery: "착불 결제",
    cashOnDeliveryDesc: "상품 도착 시 결제합니다.",
    activeOrders: "진행 중 주문",
    upcoming: "예정",
    cancelled: "취소됨",
    received: "수령 완료",
    orders: "주문",
    customerName: "고객명",
    customerContact: "고객 연락처",
    deliveryAddress: "배송 주소",
    seller: "판매자",
    sellerSupport: "판매자 지원",
    trackingNo: "운송장 번호",
    yourOrderIs: "현재 주문 상태",
    latestTrackingUpdate: "아래에서 최신 배송 추적 내역을 확인하세요.",
    returnOrder: "반품 신청",
    exchangeItem: "교환 신청",
    forDeliveryQueries: "배송 문의",
    contactUs: "문의하기",
    trackingHistory: "배송 추적 내역",
    noOrdersYet: "이 섹션에 아직 주문이 없습니다.",
    accountProfile: "내 계정 / 프로필",
    personalDetails: "개인 정보",
    dateOfBirth: "생년월일",
    gender: "성별",
    nationality: "국적",
    address: "주소",
    email: "이메일",
    resetPassword: "비밀번호 재설정",
    resetHint: "비밀번호를 변경하려면 `?tab=reset`으로 이 섹션을 여세요.",
    newPassword: "새 비밀번호",
    confirmPassword: "비밀번호 확인",
    savePassword: "비밀번호 저장",
    featured: "추천순",
    lowestToHighest: "낮은 가격순",
    highestToLowest: "높은 가격순",
    priceRange: "가격 범위",
    upTo: "최대",
    searchProducts: "상품 검색",
    results: "개 결과",
    available: "구매 가능",
    preOrder: "예약 주문",
    soldOut: "품절",
    unavailable: "구매 불가",
    addToCart: "장바구니 담기",
    noProductsFound: "상품을 찾을 수 없습니다.",
    tryDifferentSearch: "다른 검색어나 더 높은 가격 범위를 시도하세요.",
    selectSize: "사이즈 선택",
    quantity: "수량",
    outOfStock: "품절",
    buyItNow: "바로 구매",
    description: "설명",
    shippingReturns: "배송 및 반품",
    shippingReturnsText: "2-4 영업일 내 발송됩니다. 14일 반품 가능합니다.",
    details: "상세 정보",
    productNotFound: "상품을 찾을 수 없습니다.",
    backToProducts: "상품 목록으로",
    ordersLabel: "주문",
    on: "사용 중",
  },
  Japanese: {
    home: "ホーム",
    shop: "ショップ",
    album: "アルバム",
    ourProduct: "商品",
    apparel: "アパレル",
    accessories: "アクセサリー",
    allApparel: "すべてのアパレル",
    allAccessories: "すべてのアクセサリー",
    tShirts: "Tシャツ",
    hoodies: "フーディー",
    caps: "キャップ",
    keychain: "キーチェーン",
    photoStrip: "フォトストリップ",
    wrappingPaper: "ラッピングペーパー",
    sloganMuffler: "スローガンマフラー",
    notifications: "通知",
    viewAllNotifications: "すべての通知を見る",
    myProfile: "マイプロフィール",
    myOrders: "注文履歴",
    settings: "設定",
    logOut: "ログアウト",
    language: "言語",
    currency: "通貨",
    shoppingCart: "ショッピングカート",
    shippingDetails: "配送情報",
    paymentOption: "支払い方法",
    reviewItems: "配送情報へ進む前に商品を確認してください。",
    yourCartIsEmpty: "カートは空です。",
    continueShopping: "買い物を続ける",
    officialInCart: "ショッピングカート内の公式KATSEYE商品です。",
    youMayAlsoBeInterested: "こちらもおすすめ",
    shippingInsurance: "配送保険",
    protectTransit: "配送中の紛失、盗難、破損から注文を保護します。",
    orderSummary: "注文概要",
    subTotal: "小計",
    shipping: "送料",
    tax: "税金",
    totalPayable: "合計金額",
    proceedToCheckout: "安全にチェックアウト",
    satisfactionTitle: "満足保証",
    satisfactionText: "厳選されたKATSEYE商品だけを表示しています。注文に問題があればサポートへご連絡ください。",
    orderConfirmed: "注文が確定しました",
    yourOrderPlaced: "ご注文が完了しました。",
    shippingTo: "配送先",
    viewOrders: "注文を見る",
    enterShippingDetails: "配送に必要な住所と連絡先を入力してください。",
    choosePaymentMethod: "支払い方法を選択し、配送先を確認してください。",
    back: "戻る",
    fullName: "氏名",
    phoneNumber: "電話番号",
    country: "国",
    city: "市区町村",
    postalCode: "郵便番号",
    streetAddress: "住所",
    selectedShippingAddress: "選択した配送先",
    continueToPayment: "支払いへ進む",
    placeOrder: "注文する",
    completeShipping: "続行する前に配送情報をすべて入力してください。",
    emptyCart: "カートは空です。",
    creditDebitCard: "クレジット / デビットカード",
    creditDebitCardDesc: "Visa、Mastercard、AMEXが利用できます。",
    paypal: "PayPal",
    paypalDesc: "PayPal残高または登録カードで支払います。",
    cashOnDelivery: "代金引換",
    cashOnDeliveryDesc: "商品到着時に支払います。",
    activeOrders: "進行中の注文",
    upcoming: "発送予定",
    cancelled: "キャンセル済み",
    received: "受取済み",
    orders: "注文",
    customerName: "お客様名",
    customerContact: "連絡先",
    deliveryAddress: "配送先住所",
    seller: "販売者",
    sellerSupport: "販売者サポート",
    trackingNo: "追跡番号",
    yourOrderIs: "ご注文の状況",
    latestTrackingUpdate: "最新の配送状況は下記の履歴をご確認ください。",
    returnOrder: "返品する",
    exchangeItem: "交換する",
    forDeliveryQueries: "配送に関するお問い合わせ",
    contactUs: "お問い合わせ",
    trackingHistory: "追跡履歴",
    noOrdersYet: "このセクションにはまだ注文がありません。",
    accountProfile: "マイアカウント / プロフィール",
    personalDetails: "個人情報",
    dateOfBirth: "生年月日",
    gender: "性別",
    nationality: "国籍",
    address: "住所",
    email: "メール",
    resetPassword: "パスワードをリセット",
    resetHint: "パスワードを変更したい場合は `?tab=reset` でこのセクションを開いてください。",
    newPassword: "新しいパスワード",
    confirmPassword: "パスワードを確認",
    savePassword: "パスワードを保存",
    featured: "注目順",
    lowestToHighest: "価格の安い順",
    highestToLowest: "価格の高い順",
    priceRange: "価格帯",
    upTo: "最大",
    searchProducts: "商品を検索",
    results: "件",
    available: "在庫あり",
    preOrder: "予約販売",
    soldOut: "売り切れ",
    unavailable: "利用不可",
    addToCart: "カートに追加",
    noProductsFound: "商品が見つかりません。",
    tryDifferentSearch: "別の検索語かより高い価格帯を試してください。",
    selectSize: "サイズを選択",
    quantity: "数量",
    outOfStock: "在庫切れ",
    buyItNow: "今すぐ購入",
    description: "説明",
    shippingReturns: "配送と返品",
    shippingReturnsText: "2〜4営業日で発送。14日間の返品対応。",
    details: "詳細",
    productNotFound: "商品が見つかりません。",
    backToProducts: "商品一覧へ戻る",
    ordersLabel: "注文",
    on: "有効",
  },
} as const;

type TranslationKey = keyof typeof translations.English;

export const getStoredLanguage = (): StoreLanguage => {
  if (typeof window === "undefined") return "English";
  const value = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return languageOptions.includes(value as StoreLanguage) ? (value as StoreLanguage) : "English";
};

export const getStoredCurrency = (): StoreCurrency => {
  if (typeof window === "undefined") return "USD";
  const value = window.localStorage.getItem(CURRENCY_STORAGE_KEY);
  return currencyOptions.some((option) => option.code === value) ? (value as StoreCurrency) : "USD";
};

const subscribeStoreSettings = (callback: () => void) => {
  if (typeof window === "undefined") return () => {};

  const handleChange = () => callback();
  window.addEventListener("storage", handleChange);
  window.addEventListener(STORE_SETTINGS_EVENT, handleChange);

  return () => {
    window.removeEventListener("storage", handleChange);
    window.removeEventListener(STORE_SETTINGS_EVENT, handleChange);
  };
};

export const emitStoreSettingsChange = () => {
  if (typeof window === "undefined") return;
  window.dispatchEvent(new Event(STORE_SETTINGS_EVENT));
};

export const useStoreSettings = () => {
  const language = useSyncExternalStore(subscribeStoreSettings, getStoredLanguage, () => "English");
  const currency = useSyncExternalStore(subscribeStoreSettings, getStoredCurrency, () => "USD");

  const translate = (key: TranslationKey) => translations[language][key] ?? translations.English[key];

  const formatCurrency = (value: number) => {
    const config = currencyOptions.find((option) => option.code === currency) ?? currencyOptions[1];
    return new Intl.NumberFormat(config.locale, {
      style: "currency",
      currency: config.code,
      maximumFractionDigits: config.code === "KRW" || config.code === "JPY" ? 0 : 2,
    }).format(value * config.rate);
  };

  const translateCategoryText = (value: string) => {
    const mapping: Record<string, TranslationKey> = {
      "Featured": "featured",
      "Lowest to Highest": "lowestToHighest",
      "Highest to Lowest": "highestToLowest",
      "Price Range": "priceRange",
      "Search products": "searchProducts",
      "Available": "available",
      "Pre-Order": "preOrder",
      "Sold out": "soldOut",
      "Merch Category": "apparel",
      "Accessories Collection": "accessories",
      "All Apparel": "allApparel",
      "All Accessories": "allAccessories",
      "T-Shirts": "tShirts",
      "Hoodies": "hoodies",
      "Caps": "caps",
      "Keychain": "keychain",
      "Photo Strip": "photoStrip",
      "Wrapping Paper": "wrappingPaper",
      "Slogan Muffler": "sloganMuffler",
    };

    const key = mapping[value];
    return key ? translate(key) : value;
  };

  return {
    language,
    currency,
    t: translate,
    formatCurrency,
    translateCategoryText,
  };
};
